### ISSUE TITLE
RuntimeError: hook 'linear_fa_backward_hook' has changed the size of value

### ISSUE THREAD

**Issue by HaFred** [jordan-g/PyTorch-Feedback-Alignment-Layers#1]
Hi @jordan-g , 
Thank you for sharing this work. It is fascinating. I ran into an error `RuntimeError: hook 'linear_fa_backward_hook' has changed the size of value`. Basically, the `grad_input` of `linear_fa_backward_hook` messed up if I set the `Linear(in_channels, out_channel, bias=False)`. But I thought, the should correctly return `grad_input` with only `act_grad` and `weight_grad`, but no `bias_grad`.
```
def linear_fa_backward_hook(module, grad_input, grad_output):
    if grad_input[1] is not None:
        grad_input_fa = grad_output[0].mm(module.weight_fa)
        return (grad_input[0], grad_input_fa) + grad_input[2:]
```
What do you think?

**Comment by jordan-g** [comment]
Hi HaFred,

Apologies for the long delay in replying. You're right, the code was not working correctly when bias was set to False. I've fixed it in the latest commit. Thanks for bringing up this issue!
